export let quotes_list = [
{quote: "I do not fear computers. I fear lack of them." , author: " Isaac Asimov"},
{quote: "A computer once beat me at chess, but it was no match for me at kick boxing." , author: " Emo Philips"},
{quote: "Computer Science is no more about computers than astronomy is about telescopes." , author: " Edsger W. Dijkstra"},
{quote: "The computer was born to solve problems that did not exist before." , author: " Bill Gates"},
{quote: "Software is like entropy: It is difficult to grasp, weighs nothing, and obeys the Second Law of Thermodynamics; i.e., it always increases."   , author: " Norman Augustine"},
{quote: "Software is a gas; it expands to fill its container." , author: " Nathan Myhrvold"},
{quote: "All parts should go together without forcing.  You must remember that the parts you are reassembling were disassembled by you.  Therefore, if you can’t get them together again, there must be a reason.  By all means, do not use a hammer."    , author: " IBM Manual, 1925"},
{quote: "Standards are always out of date.  That’s what makes them standards." , author: " Alan Bennett"},
{quote: "Physics is the universe’s operating system."  , author: " Steven R Garman"},
{quote: "It’s hardware that makes a machine fast.  It’s software that makes a fast machine slow." , author: " Craig Bruce"},
{quote: "Imagination is more important than knowledge.  For knowledge is limited, whereas imagination embraces the entire world, stimulating progress, giving birth to evolution."    , author: " Albert Einstein"},
{quote: "The greatest enemy of knowledge is not ignorance, it is the illusion of knowledge." , author: " Stephen Hawking"},
{quote: "The more you know, the more you realize you know nothing." , author: " Socrates"},
{quote: "Tell me and I forget.  Teach me and I remember.  Involve me and I learn." , author: " Benjamin Franklin"},
{quote: "Real knowledge is to know the extent of one’s ignorance." , author: " Confucius"},
{quote: "If people never did silly things, nothing intelligent would ever get done." , author: " Ludwig Wittgenstein"},
{quote: "Getting information off the Internet is like taking a drink from a fire hydrant.", author: " Mitchell Kapor"},
{quote: "If you think your users are idiots, only idiots will use it.", author: " Linus Torvalds"},
{quote: "From a programmer’s point of view, the user is a peripheral that types when you issue a read request." , author: " P. Williams"},
{quote: "Where is the ‘any’ key?" , author: " Homer Simpson"},
{quote: "Computers are good at following instructions, but not at reading your mind." , author: " Donald Knuth"},
{quote: "There is only one problem with common sense; it’s not very common." , author: " Milt Bryce"},
{quote: "Your most unhappy customers are your greatest source of learning." , author: " Bill Gates"},
{quote: "Let us change our traditional attitude to the construction of programs: Instead of imagining that our main task is to instruct a computer what to do, let us concentrate rather on explaining to human beings what we want a computer to do."    , author: " Donald E. Knuth"},
{quote: "The Internet?  We are not interested in it." , author: " Bill Gates, 1993"},
{quote: "The best way to get accurate information on Usenet is to post something wrong and wait for corrections." , author: " Matthew Austern"},
{quote: "The most likely way for the world to be destroyed, most experts agree, is by accident.  That’s where we come in; we’re computer professionals.  We cause accidents."   , author: " Nathaniel Borenstein"},
{quote: "Pessimists, we’re told, look at a glass containing 50% air and 50% water and see it as half empty.  Optimists, in contrast, see it as half full.  Engineers, of course, understand the glass is twice as big as it needs to be.", author: " Bob Lewis"},
{quote: "In a room full of top software designers, if two agree on the same thing, that’s a majority." , author: " Bill Curtis"},
{quote: "It should be noted that no ethically-trained software engineer would ever consent to write a DestroyBaghdad procedure.  Basic professional ethics would instead require him to write a DestroyCity procedure, to which Baghdad could be given as a parameter."    , author: " Nathaniel S. Borenstein"},
{quote: "Mostly, when you see programmers, they aren’t doing anything.  One of the attractive things about programmers is that you cannot tell whether or not they are working simply by looking at them.  Very often they’re sitting there seemingly drinking coffee and gossiping, or just staring into space.  What the programmer is trying to do is get a handle on all the individual and unrelated ideas that are scampering around in his head."    , author: " Charles M. Strauss"},
{quote: "If you think you are worth what you know, you are very wrong.  Your knowledge today does not have much value beyond a couple of years.  Your value is what you can learn and how easily you can adapt to the changes this profession brings so often."    , author: " Jose M. Aguilar"},
{quote: "Programs must be written for people to read, and only incidentally for machines to execute.", author: " Abelson and Sussman"},
{quote: "Commenting your code is like cleaning your bathroom : you never want to do it, but it really does create a more pleasant experience for you and your guests."    , author: " Ryan Campbell"},
{quote: "We have to stop optimizing for programmers and start optimizing for users." , author: " Jeff Atwood"},
{quote: "Low-level programming is good for the programmer’s soul.", author: " John Carmack"},
{quote: "It’s OK to figure out murder mysteries, but you shouldn’t need to figure out code.  You should be able to read it."    , author: " Steve McConnell"},
{quote: "If we wish to count lines of code, we should not regard them as ‘lines produced’ but as ‘lines spent.’", author: " Edsger Dijkstra"},
{quote: "Programming can be fun, so can cryptography; however they should not be combined.", author: " Kreitzberg and Shneiderman"},
{quote: "Before software should be reusable, it should be usable.", author: " Ralph Johnson"},
{quote: "If you automate a mess, you get an automated mess.", author: " Rod Michael"},
{quote: "Looking at code you wrote more than two weeks ago is like looking at code you are seeing for the first time.", author: " Dan Hurvitz"},
{quote: "It is easier to change the specification to fit the program than vice versa.", author: " Alan Perlis"},
{quote: "Less than 10% of the code has to do with the ostensible purpose of the system; the rest deals with input-output, data validation, data structure maintenance, and other housekeeping.", author: " Mary Shaw"},
{quote: "If you have a procedure with ten parameters, you probably missed some.", author: " Alan Perlis"},
{quote: "How rare it is that maintaining someone else’s code is akin to entering a beautifully designed building, which you admire as you walk around and plan how to add a wing or do some redecorating. More often, maintaining someone else’s code is like being thrown headlong into a big pile of slimy, smelly garbage.", author: " Bill Venners"},
{quote: "Code generation, like drinking alcohol, is good in moderation.", author: " Alex Lowe"},
{quote: "Simplicity, carried to the extreme, becomes elegance.", author: " Jon Franklin"}
];
